name: CI - URL Shortener Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Composer install
        run: composer install --no-interaction

      - name: ENV setup
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: SQLite setup
        run: touch /home/runner/work/url-shortner/url-shortner/database/database.sqlite

      - name: Database migrate
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /home/runner/work/url-shortner/url-shortner/database/database.sqlite

      - name: Run the test
        run: php artisan test --stop-on-failure 2>&1
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /home/runner/work/url-shortner/url-shortner/database/database.sqlite
          APP_DEBUG: true
          LOG_CHANNEL: stderr